copy thomas_season01.xml thomas_season02.xml /Y
copy thomas_season02.xml thomas_season03.xml /Y
copy thomas_season03.xml thomas_season04.xml /Y
copy thomas_season04.xml thomas_season05.xml /Y
copy thomas_season05.xml thomas_season06.xml /Y
copy thomas_season06.xml thomas_season07.xml /Y
copy thomas_season07.xml thomas_season08.xml /Y
copy thomas_season08.xml thomas_season09.xml /Y
copy thomas_season09.xml thomas_season10.xml /Y
copy thomas_season10.xml thomas_season11.xml /Y
copy thomas_season11.xml thomas_season12.xml /Y
copy thomas_season12.xml thomas_season13.xml /Y
copy thomas_season13.xml thomas_season14.xml /Y
copy thomas_season14.xml thomas_season15.xml /Y
copy thomas_season15.xml thomas_season16.xml /Y
copy thomas_season16.xml thomas_season17.xml /Y